### ISSUE TITLE
Authentication without upnp?

### ISSUE THREAD

**Issue by davglass** [flux3dp/fluxclient#50]
How can I generate and add a new RSA key to my delta without using the upnp task? It seems that's the only way to add the RSA key even if I already know the devices IP address and password.

The reason is that I'm using a Docker container to handle all of the flux client code.  I've build a local web service that shows me the camera and status of my delta from any device on the network :)

The issue is that the Docker container isn't on the same subnet, so a upnp discover will fail. If I have the key (snagged from the UI's localStorage) I can successfully use the `flux_camera` and `flux_robot` tools to get the information that I need. I can't seem to figure out how to create a new RSA key and add it to the device without using the upnp task.

**Comment by yagami-cerberus** [comment]
Upnp currently is the only way to add new RSA key. I found out that upnp task is not work properly when device IP address is in different subnet. We will try to fix it in next release.

**Comment by davglass** [comment]
Cool, at least I didn't miss anything. I ran into the setup issue as my wife and hardwired networks are on two different subnets. I had to put my laptop on wifi in order to control the printer. It would be nice if we had a way to connect via IP without `upnp`. :)

**Comment by yagami-cerberus** [comment]
Hello, the last release fix the upnp over different subnet issue. It is possible to connect and control FLUX without upnp.

Upnp is used to discover and configure your device, if you want to control your device, you can simply import `fluxclient.robot.robot` module and use `FluxRobot` class to create a new connection with device.

**Comment by davglass** [comment]
Awesome! I'll give it a shot. I finally got a working `Dockerfile` that will create a ghost WebSocket server and I have a custom Node app that monitors my printer with it! The only issue left was creating the Key file at start up..
